name: Scheduled Sticker Scraping

on:
  schedule:
    # Run 6 times a day at 4-hour intervals: 00:00, 04:00, 08:00, 12:00, 16:00, 20:00 UTC
    - cron: '0 0,4,8,12,16,20 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape-stickers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y webp
        
    - name: Install dependencies
      run: npm install
      
    - name: Create logs directory
      run: mkdir -p logs
      
    - name: Run sticker scraping
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        SUPABASE_BUCKET_NAME: ${{ vars.SUPABASE_BUCKET_NAME || 'sticker-packs' }}
        MAX_PACKS_PER_RUN: ${{ vars.MAX_PACKS_PER_RUN || '50' }}
        DELAY_BETWEEN_REQUESTS: ${{ vars.DELAY_BETWEEN_REQUESTS || '2000' }}
        MAX_RETRIES: ${{ vars.MAX_RETRIES || '3' }}
        LOG_LEVEL: ${{ vars.LOG_LEVEL || 'info' }}
      run: node index.js recommended
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scraping-logs-${{ github.run_number }}
        path: logs/
        retention-days: 7
        if-no-files-found: ignore
        
    - name: Notify on failure
      if: failure()
      run: |
        echo "Scraping job failed at $(date)"
        echo "Check the logs artifact for details"