name: Scheduled Sticker Scraping

on:
  schedule:
    # Run every 6 hours: 00:00, 06:00, 12:00, 18:00 UTC (otimizado)
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape-stickers:
    runs-on: ubuntu-latest
    timeout-minutes: 330 # 5.5 horas (margem de segurança para limite de 5h)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webp libwebp-dev

      - name: Verify WebP tools
        run: |
          which cwebp
          which dwebp  
          which webpmux
          webpmux -version || echo "webpmux version check failed"

      - name: Install dependencies
        run: npm install

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run sticker scraping
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          SUPABASE_BUCKET_NAME: ${{ vars.SUPABASE_BUCKET_NAME || 'sticker-packs' }}
          MAX_RUNTIME_HOURS: 5 # Limite de 5 horas
          MAX_PACKS_PER_RUN: ${{ vars.MAX_PACKS_PER_RUN || '100' }}
          DELAY_BETWEEN_REQUESTS: ${{ vars.DELAY_BETWEEN_REQUESTS || '2000' }}
          MAX_RETRIES: ${{ vars.MAX_RETRIES || '3' }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL || 'info' }}
        run: |
          echo "🚀 Iniciando scraping automático (limite: 5h)"
          echo "⏰ Horário de início: $(date)"
          node index.js full
          echo "✅ Scraping finalizado"
          echo "⏰ Horário de término: $(date)"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraping-logs-${{ github.run_number }}
          path: logs/
          retention-days: 7
          if-no-files-found: ignore

      - name: Notify on failure
        if: failure()
        run: |
          echo "Scraping job failed at $(date)"
          echo "Check the logs artifact for details"
